spring.application.name=forum_hub

spring.datasource.url=jdbc:mysql://localhost/forum_hub?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${STUDYHUB_MAIL_USERNAME}
spring.mail.password=${STUDYHUB_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

github.oauth.clienteId={GITHUB_CLIENT_ID}
github.oauth.clientSecret={GITHUB_CLIENT_SECRET}

google.oauth.clienteId={GOOGLE_CLIENT_ID}
google.oauth.clientSecret={GOOGLE_CLIENT_SECRET}